# Site settings
title: goldpigfly's blog
description: 혼자 놀기 위해 만든 블로그
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "" # "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url: "goldpigfly.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: "goldpigfly" #github username
repo: goldpigfly #github repository
branch: master #branch
relative_source: #../hanuman/ #source directory
destination: #../hanuman-pages/ #destination directory
production_url: # https://samanyougarg.com/
source_url: https://goldpigfly.github.io/goldpigfly.github.io/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
